### ISSUE TITLE
Require Image not work

### ISSUE THREAD

**Issue by punjasin** [WrathChaos/react-native-progressive-fast-image#1]
i have function that check url is null or not if is empty it will load local image instead and i found out that
require is not work 
even i hardcode image prop to
require('../../../assets/img/no_image.png');
it not work if i swap back to normal fastimage it work
problem is it crash on android and that issue is fix in this lib

**Comment by kuraydev** [comment]
Hello @punjasin,
Let me test very fast :)

**Comment by punjasin** [comment]
further investigation for me i found that if we set fallback to true for use normal image component it will cause this to happen it also cause on fast-image library so maybe we can close this and open issue on fast image instead

**Comment by kuraydev** [comment]
If you share the issue link with me, I can also follow the issue :)

**Comment by punjasin** [comment]
https://github.com/DylanVann/react-native-fast-image/issues/746 here is the issue i open :)
