### ISSUE TITLE
image. not show, switch back to FastImage work

### ISSUE THREAD

**Issue by fukemy** [WrathChaos/react-native-progressive-fast-image#10]
Hi, i dont know whats happen, can u take a look with my video below:

https://user-images.githubusercontent.com/8202437/182327378-ad7b9402-796c-4495-959e-415d3f6ca6e0.mov

**Comment by fukemy** [comment]
i putted:

```

                onError={error => console.log('error', error)}
                onImageLoad={console.log('onImageLoad')}
                onLoadEnd={console.log('onLoadEnd')}
```
then the log only show:
onImageLoad
onLoadEnd

**Comment by fukemy** [comment]
Hi @WrathChaos , did u find any problem, and do you want mote informations?

**Comment by kuraydev** [comment]
Hello @fukemy 
I am extremely sorry. Forgot this issue :( 

Can you please try it out with [Version 1](https://github.com/WrathChaos/react-native-progressive-fast-image/releases/tag/1.0.0) 

I am glad to help you with this issue.

**Comment by fukemy** [comment]
ok thanks, I will check it
