### ISSUE TITLE
onLoad Props in <ProgressiveFastImage />

### ISSUE THREAD

**Issue by vinodsnayvik** [WrathChaos/react-native-progressive-fast-image#12]
Hello,

I saw using adding onLoad props but <ProgressiveFastImage /> does not trigger after loaded.

Is onLoad props available or not in this library ?

**Comment by kuraydev** [comment]
Hello @vinodsnayvik 

[Version 1](https://github.com/WrathChaos/react-native-progressive-fast-image/releases/tag/1.0.0) is released :) 

You can use `onLoad` and others as well :) Please take a look at it
