### ISSUE TITLE
publish 0.2.2 on npm

### ISSUE THREAD

**Issue by efstathiosntonas** [WrathChaos/react-native-progressive-fast-image#2]
Hi, can you please publish the new version on npm? Thanks

**Comment by kuraydev** [comment]
Hello @efstathiosntonas,
I will publish it today :) I will inform you

**Comment by efstathiosntonas** [comment]
Thanks a lot!

**Comment by kuraydev** [comment]
@efstathiosntonas can you please try the v0.2.2? I published it :)

**Comment by efstathiosntonas** [comment]
I’ve updated it all good! Thanks for your hard work!

**Comment by kuraydev** [comment]
@efstathiosntonas I will update one more version for the loading component, it is not working what I am expected :)

**Comment by efstathiosntonas** [comment]
Yeah, i think it’s not showing the component, right?

**Comment by kuraydev** [comment]
@efstathiosntonas #3 let's continue on there. Also, PR's are welcome btw :)
