### ISSUE TITLE
Loading Custom Component Feature

### ISSUE THREAD

**Issue by kuraydev** [WrathChaos/react-native-progressive-fast-image#3]
Loading should be a customizable

**Comment by efstathiosntonas** [comment]
Hi @WrathChaos, we've implemented/fixed the loading custom component, take a look in this [example](https://github.com/georstat/react-native-image-cache/tree/main/example/src) and the [source code](https://github.com/georstat/react-native-image-cache/blob/2c3ddd9de22e5a4b64c1e3aa14cf6583e7016cab/src/CachedImage.tsx#L164). Unfortunately  i don't have time for a PR :(
