### ISSUE TITLE
Update React to 17.x.x

### ISSUE THREAD

**Issue by wmonecke** [WrathChaos/react-native-progressive-fast-image#5]
I think it would be awesome to update this library to React 17 so it is compatible with RN 0.64.

Do you want me to create a PR?

**Comment by kuraydev** [comment]
I will do this asap :)

**Comment by wmonecke** [comment]
@WrathChaos Awesome!

**Comment by kuraydev** [comment]
Hello @wmonecke,
[Version 0.2.4](https://github.com/WrathChaos/react-native-progressive-fast-image/releases/tag/0.2.4)  is available right now. 
Also, the example is upgraded to the latest versions :) 
Please check it out.
