### ISSUE TITLE
prop to set the amount blur

### ISSUE THREAD

**Issue by Garamani** [WrathChaos/react-native-progressive-fast-image#6]
Thank you for this great package, works well the only missing feature is being able to set the amount of blurriness. The default value, in my opinion, is too much.

**Comment by kuraydev** [comment]
I will do this tomorrow :)

**Comment by kuraydev** [comment]
Hello @Garamani,
The new 0.2.4 version is available, also you can change the `blurRadius` :)
## [Version 0.2.4](https://github.com/WrathChaos/react-native-progressive-fast-image/releases/tag/0.2.4)

**Comment by Garamani** [comment]
@WrathChaos 
Thank you for taking the time to add this useful feature. I tested and It works well. Happy Coding :)

**Comment by dancixx** [comment]
@WrathChaos Is `blurRadius` a required prop or just a mistake in the typedef?

**Comment by kuraydev** [comment]
> @WrathChaos Is `blurRadius` a required prop or just a mistake in the typedef?

🤦

Complete my bad, thank you so much for reporting this mistake :) I'm going to release a new version now.

**Comment by kuraydev** [comment]
@dancixx Thank you so much for the reporting again :) 

I fixed it on [Release 0.2.5](https://github.com/WrathChaos/react-native-progressive-fast-image/releases/tag/0.2.5) 

Thank you again
